# api.jl — the curated top-level export surface (Stage 4c).
#
# This file is the ONLY export site of the main module. The policy
# (docs/src and the Stage-4 plan): family submodules export their own
# public surface; the top level re-exports the curated user-facing core —
# upstream-compatible parabolic names, problem/solution/algorithm types,
# mesh builders, BC constructors, user accessors, and the capability API.
# Supported-but-unexported names carry `@compat public` markers in their
# owning submodules. Nothing from `Experimental` is re-exported here, and
# canonical family-specific BC access is module-qualified
# (e.g. `Parabolic.DirichletBC`). Deprecated aliases (Stage 4b) live in
# FiniteVolumeMethod.jl next to `using .Parabolic`, not here.

# --- SciML entry points and solution accessors (7) ---
export compute_initial_dt,
    remake,
    sciml_problem,
    solution_accessor,
    solution_coordinates,
    solution_snapshot,
    solve

# --- Capability and validation-maturity API (9) ---
export capability_matrix,
    feature_claim_policy,
    feature_limitations,
    feature_maturity,
    feature_required_ladder_stages,
    feature_role,
    feature_solver_family,
    feature_validation_status,
    supported_features

# --- Geometry: meshes and coordinate systems (8) ---
export Cartesian,
    Cylindrical,
    FVMGeometry,
    StructuredMesh1D,
    StructuredMesh2D,
    StructuredMesh3D,
    n_cells,
    ncells

# --- Numerics: EOS, limiters, backends (10) ---
export IdealGasEOS,
    KorenLimiter,
    MinmodLimiter,
    OspreLimiter,
    SuperbeeLimiter,
    VanLeerLimiter,
    minmod,
    pressure,
    temperature,
    total_energy

# --- Vertex conditions (upstream-compatible parabolic BC/IC API) (9) ---
export BoundaryConditions,
    ConditionType,
    Conditions,
    Constrained,
    Dirichlet,
    Dudt,
    InternalConditions,
    Neumann,
    Robin

# --- Parabolic cell-vertex solver (14) ---
export AbstractBoundaryCondition,
    AbstractFVMTemplate,
    DiffusionEquation,
    FVMProblem,
    FVMSystem,
    LaplacesEquation,
    LinearReactionDiffusionEquation,
    MeanExitTimeProblem,
    ParticleTracker,
    PoissonsEquation,
    SteadyFVMProblem,
    Variable,
    compute_flux,
    pl_interpolate

# --- Collocated incompressible solver and physics (80) ---
export CollocatedArrheniusReaction,
    CollocatedScalarField,
    CollocatedVectorField,
    CombustionComponent,
    CombustionProperties,
    ConvectiveOutletBC,
    CustomBC,
    CyclicBC,
    DDES,
    DynamicSmagorinsky,
    EddyDissipationConcept,
    EddyDissipationModel,
    FVMSolverConfig,
    FaceFluxField,
    FieldSolverConfig,
    FixedPressureBC,
    FixedVelocityBC,
    FlowRateInletBC,
    FluidThermalProperties,
    FvDOMModel,
    IncompressibleModel,
    IncompressibleProblem,
    SteadyIncompressibleProblem,
    IncompressibleSolution,
    IncompressibleState,
    InletOutletBC,
    KOmega,
    KappaOmegaSST,
    MultiStepMechanism,
    NoSlipWallBC,
    P1Model,
    PIMPLE,
    PISO,
    PressureInletVelocityBC,
    RadiationComponent,
    SIMPLE,
    STEFAN_BOLTZMANN,
    SlipWallBC,
    Smagorinsky,
    SolidBodyMotion,
    SolidThermalProperties,
    SpalartAllmaras,
    SpeciesState,
    StandardKEpsilon,
    StokesDrag,
    SymmetryBC,
    ThermalComponent,
    TimeDependentVelocityBC,
    TotalPressureBC,
    TwoFluidProperties,
    TwoFluidSolver,
    TwoPhaseProperties,
    TurbulenceComponent,
    VOFState,
    WALE,
    WallFunctionBC,
    ZeroGradientBC,
    advance_particles!,
    compute_forces,
    divergence,
    evaluate,
    gradient,
    has_combustion,
    has_mrf_zones,
    has_porous_zones,
    has_radiation,
    has_thermal,
    has_turbulence,
    inject_particles!,
    is_plain_flow,
    marshak_wall_bc,
    set_particle_properties!,
    solve_ale,
    solve_p1_radiation,
    solve_simple_reacting,
    solve_simple_thermal,
    solve_simple_turbulent,
    solve_vof,
    thermal_inlet_bc,
    thermal_insulated_bc

# --- Hyperbolic cell-centered solver (66) ---
export AMRGrid,
    AMRProblem,
    ArrheniusReaction,
    CellCenteredMUSCL,
    CharacteristicWENO,
    ChemistrySource,
    CoolingSource,
    DirichletHyperbolicBC,
    EulerEquations,
    GRMHDEquations,
    GradientRefinement,
    HLLCSolver,
    HLLDSolver,
    HLLSolver,
    HallMHDEquations,
    HyperbolicProblem,
    HyperbolicProblem2D,
    HyperbolicProblem3D,
    IdealMHDEquations,
    KerrMetric,
    LaxFriedrichsSolver,
    LieTrotterSplitting,
    MinkowskiMetric,
    NavierStokesEquations,
    NoReconstruction,
    NoSlipBC,
    NullSource,
    PPMReconstruction,
    PeriodicHyperbolicBC,
    ReactionMechanism,
    ReactiveEulerEquations,
    ReflectiveBC,
    ResistiveMHDEquations,
    SRHydroEquations,
    SRMHDEquations,
    SchwarzschildMetric,
    ShallowWaterEquations,
    StrangSplitting,
    TransmissiveBC,
    TwoFluidEquations,
    WENO3,
    WENO5,
    active_blocks,
    block_cell_center,
    compute_divB,
    conserved_to_primitive,
    get_conserved,
    get_coordinates,
    get_ct_state,
    get_primitive,
    hall_flux_x,
    initialize_ct_from_potential!,
    max_active_level,
    max_divB,
    max_wave_speed,
    mhd_stage_limiter,
    nvariables,
    ohmic_heating,
    physical_flux,
    primitive_to_conserved,
    regrid!,
    resistive_flux_x,
    solve_amr,
    solve_coupled,
    to_primitive,
    whistler_speed

# --- I/O and session tooling (1) ---
export conserved_totals
